### PR TITLE
Experimental 2015/11/16

### PR DESCRIPTION
**Pull request by justinstoller**
To create this I branched off of openstack-infra/jenkins-job-builder#master and then rebase puppetlabs/jenkins-job-builder#experimental onto it. There were four commits listed:

```
pick 81ec58c Fix Builder.update_job() on Python 3
pick f4088fc Ensure tests run with ConfigParser object
pick 52a4422 Take parameter order from yaml in trigger_parameterized_builds
pick 34ebf95 Remove the worst debug message in the history of debug messages.
```

However all but

```
pick 34ebf95 Remove the worst debug message in the history of debug messages.
```

seemed to be in upstream master in one form or another (see [81ec58c](https://github.com/openstack-infra/jenkins-job-builder/commit/81ec58c), [f4088fc](https://github.com/openstack-infra/jenkins-job-builder/commit/f4088fc), and [52a4422](https://github.com/openstack-infra/jenkins-job-builder/commit/52a4422)).

So I cleanly rebased 34ebf95 on to the upstream master and ... thats this. I'm unclear about whether the merge conflicts are coming from other merge commits within experimental or from something I'm missing. It seems that we're deploying out of time based branches, so this may be unnecessary but I figured the visibility to the content of the branch would be good. Alternatively, maybe I should have branched off of the last time based branch?

ping @puppetlabs/jjb

### CODE REVIEW

**Comment by rick** [comment]
Hrm.  Looking. This looks suspicious.

**Comment by rick** [comment]
So, my first reaction was "stop trying to rebase", and instead generated a merge:

```
$ git clone https://github.com/puppetlabs/jenkins-job-builder.git
$ cd jenkins-job-builder/
$ git remote add upstream https://github.com/openstack-infra/jenkins-job-builder.git
$ git fetch upstream
$ git log upstream/master..origin/experimental | grep '^commit'
commit 34ebf95870cc44595457c14779124f418cd381ef
commit 52a4422eaec18e5dd98ddd294a9f09c332eae3c9
commit f4088fc29276cb356a1c686517f65378f5c7bd8d
commit 81ec58c896431268a929d2fa0cc69ebda4d5d9e3
commit dda134c76a5716296b87c0a09a038211d3702831
$ git checkout -b rick-experimental-20151117
$ git merge upstream/master
# ...
Unmerged paths:
  (use "git add <file>..." to mark resolution)

    both modified:   doc/source/installation.rst
    both modified:   jenkins_jobs/modules/publishers.py
    both modified:   tests/base.py
    both modified:   tests/builder/test_builder.py
    both modified:   tox.ini

Tue Nov 17 11:23:20 chenrezig ~/pl/jenkins-job-builder
 (rick-experimental-20151117 *+|MERGING) % ▸ gd tests/base.py 
diff --cc tests/base.py
index c7caef0,662a117..0000000
--- a/tests/base.py
+++ b/tests/base.py
@@@ -124,10 -140,7 +140,20 @@@ class BaseTestCase(LoggingFixture)
          if not self.in_filename:
              return

++<<<<<<< HEAD
 +        config = configparser.ConfigParser()
 +        config.readfp(StringIO(DEFAULT_CONF))
 +        if self.conf_filename is not None:
 +            config.readfp(io.open(self.conf_filename, 'r', encoding='utf-8'))
++||||||| merged common ancestors
++        if self.conf_filename is not None:
++            config = configparser.ConfigParser()
++            config.readfp(io.open(self.conf_filename, 'r', encoding='utf-8'))
++        else:
++            config = {}
++=======
+         config = self._get_config()
++>>>>>>> upstream/master

          expected_xml = self._read_utf8_content()
          yaml_content = self._read_yaml_content(self.in_filename)
@@@ -176,13 -190,10 +203,24 @@@

  class SingleJobTestCase(BaseTestCase):
      def test_yaml_snippet(self):
+         config = self._get_config()
+ 
          expected_xml = self._read_utf8_content()

++<<<<<<< HEAD
 +        config = configparser.ConfigParser()
 +        config.readfp(StringIO(DEFAULT_CONF))
 +        if self.conf_filename is not None:
 +            config.readfp(io.open(self.conf_filename, 'r', encoding='utf-8'))
 +
++||||||| merged common ancestors
++        if self.conf_filename:
++            config = configparser.ConfigParser()
++            config.readfp(io.open(self.conf_filename, 'r', encoding='utf-8'))
++        else:
++            config = None
++=======
++>>>>>>> upstream/master
          parser = YamlParser(config)
          parser.parse(self.in_filename)
```

Interesting, so "both" modified `tests/base.py`.  Seems unlikely.

Pulling up the history pages on both repositories for those files:
- ours: https://github.com/puppetlabs/jenkins-job-builder/commits/experimental/tests/base.py
- theirs: https://github.com/openstack-infra/jenkins-job-builder/commits/master/tests/base.py

Notice our head commit, on our branch:

history_for_tests_base_py_-_puppetlabs_jenkins-job-builder

on their branch:

history_for_tests_base_py_-_openstack-infra_jenkins-job-builder

So, our HEAD commit was accepted into their branch with a different author and SHA. Did they force-push a publicly visible branch? Quite possibly (hint: only jerks do that). Did we import local commits in hopes that they would be accepted upstream and then try to rebase against a different public history? Quite possibly.

**Comment by justinstoller** [comment]
I think @waynr could probably answer both of those questions.

If they're force pushing to their master branch then trying to sort this out my be moot.

If not, then I assume we should take a hit and fix this base branch so that it matches upstream? I'm also wondering if we should continue to deploy out of an experimental branch if the only difference is a single debug commit? And if we do want to continue to maintain this branch, what is a good way to manage it going forward that avoids issues like this in the future?

**Comment by rick** [comment]
I'm :+1: on trying to kill experimental branches and running with upstream if possible. I've seen worlds where numerous upstream repos were tracked with local change repos/branches and it's definitely a drag. There are good reasons to do it, but when possible, getting back to upstream is usually a win.

**Comment by waynr** [comment]
Also :+1: to moving toward running from upstream.

If we are going to do this, we should install JJB from pypi rather than use the submodule.

**Comment by rick** [comment]
Is this still a thing? (Just going back through my `involved:rick` PRs and tidying up)

**Comment by waynr** [comment]
@rick as far as I know this branch isn't necessary for anything we are currently doing with JJB at puppet. In fact, we aren't even using the JJB git submodule anymore, we are installing it directly from pypi.

**Comment by rick** [comment]
Closing. Git has our back.

**Pull request closed without merging**
