### PR TITLE
(maint) Add *.eggs to .gitignore

### PR DESCRIPTION
**Pull request by nwolfe**
Otherwise users of ci-job-configs will commonly have a dirty jenkins-job-builder submodule

### CODE REVIEW

**Comment by nwolfe** [comment]
Ping @waynr

**Comment by sbeaulie** [comment]
:+1: :sun_with_face:

**Comment by waynr** [comment]
@nwolfe this patch needs to be submitted to the upstream project before they can be considered to be merged here. Instructions for doing so can be found here: https://github.com/puppetlabs/jenkins-job-builder#developers

The reason they need to be submitted upstream is that the more cruft we add into this fork, the longer we will be stuck using it rather than upstream. Getting changes merged in upstream as a requirement for merging into our fork ensures that we already have that process, which can take a while, underway.

**Comment by nwolfe** [comment]
@waynr Thanks, that's good to know, and I agree with that sentiment.

I don't think we should bother doing that though.  I'll just add a personal gitignore, and others will have to do the same if it bugs them having a dirty submodule.

**Pull request closed without merging**
